### ISSUE TITLE
scripts folder is missing

### ISSUE THREAD

**Issue by nara** [aws-samples/getting-started-with-amazon-redshift-data-api#1]
hi, can you please push scripts folder under stepfunction use-case folder? 

https://github.com/aws-samples/getting-started-with-amazon-redshift-data-api/blob/main/use-cases/etl-orchestration-with-step-functions/scripts/setup_sales_data_pipeline.sql

returns 404

**Comment by itsDZhang** [comment]
Hi @nara, 

Thank you feedback, added :)
