### ISSUE TITLE
getting-started-with-amazon-redshift-data-api

### ISSUE THREAD

**Issue by adityag020** [aws-samples/getting-started-with-amazon-redshift-data-api#2]
Hi,

I was going through this use case for my WEB UI. While deploying the cloudformation template, I'm facing issue with Initialization steps resource creation mentioned in cloudformation template. It is failing to create but every other resources will be created as we hit create stack. 

Suggest some steps to overcome that particular resource failure.

Regards,
Aditya

<img width="491" alt="Resource Failure" src="https://user-images.githubusercontent.com/93257695/139051212-f6e1717c-a4ff-491e-a377-7ad8050a869b.PNG">

<html>
<body>
<div style="box-sizing: border-box; font-family: &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px;">

InitializationSteps | ED-POA-InitializationSteps-1ARPZV595URQR | Custom::SetupRedshiftLambdaFunction | CREATE_FAILED | CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [468a0bdb-b825-4b12-b735-e33615bda333]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation  can attach the updated version. | -
-- | -- | -- | -- | -- | --

</div>
</body>
</html>

**Comment by itsDZhang** [comment]
Hi @adityag020, which use-case are you referring to?

**Comment by guptadi06** [comment]
> Hi @adityag020, which use-case are you referring to?

Hi, I was facing issue with query script for 1st use case and now the issue is resolved now. Thanks for reply.

**Comment by itsDZhang** [comment]
Awesome 👍
