### ISSUE TITLE
Parameterized query not working with unload operation

### ISSUE THREAD

**Issue by causalbody** [aws-samples/getting-started-with-amazon-redshift-data-api#4]
When running a parameterized query wrapped over an "unload" operation the "execute statement" results in a 400 validation.

com.amazonaws.services.redshiftdataapi.model.ValidationException: Parameters list contains unused parameters. Unused parameters: [id] (Service: AWSRedshiftDataAPI; Status Code: 400; Error Code: ValidationException

The unload query is of the pattern

`unload('select * from table where id=:id') to '<s3location>' iam_role '<arn>' maxfilesize 6 GB CSV parallel off`

Code snippet
```
    executeStatementRequest.setSql(sql);

    SqlParameter parameter = new SqlParameter();

    parameter.setName("id");

    parameter.setValue(id); 
```

Artifact: com.amazonaws:aws-java-sdk-redshiftdataapi:1.12.122

On excluding unload and just using the query then execution goes fine.

**Comment by causalbody** [comment]
Any thoughts from developer community? Unload operation is likely exposed to sql injection without the parameter support.

**Comment by itsDZhang** [comment]
@causalbody 

Single quotes are not supported in parameterization. Please reopen this ticket if the issue is not resolved.
