### ISSUE TITLE
Slight error

### ISSUE THREAD

**Issue by alvarogt99** [aws-samples/getting-started-with-amazon-redshift-data-api#7]
Hello, good day. I have found a slight error in your code in the 'analytical-reporting-event-driven-web-app' use case in the 'script.sh' on line 46. It checks the status of output.json instead of output1.json. I am sending it to you in case you want to correct it because, with this issue, the Websockets were not being created correctly for me.

while [ "$status" != "CREATE_COMPLETE" ]
do
   aws cloudformation describe-stacks --stack-name BackendSetup > output1.json
   status=$(jq '.Stacks[].StackStatus' output1.json | sed -e 's/^"//' -e 's/"$//')
done
aws cloudformation describe-stacks --stack-name BackendSetup > output1.json

Interesting solution. 
Greetings, thank you.

**Comment by vlmpk2003** [comment]
Hello, Good Day, Thanks for pointing this out. The code is corrected now. 

Hope the solution seems useful.
